
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yyget_lval
#define yyget_lval_ALREADY_DEFINED
#else
#define yyget_lval yyget_lval
#endif

#ifdef yyset_lval
#define yyset_lval_ALREADY_DEFINED
#else
#define yyset_lval yyset_lval
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 110
#define YY_END_OF_BUFFER 111
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[388] =
    {   0,
        0,    0,  111,  109,  108,  108,   96,  109,  102,   95,
      109,   90,   91,  100,   99,   87,   98,   94,  101,   53,
       52,   88,   84,  103,   89,  104,  107,   50,   50,   92,
       93,  105,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   85,  106,
       86,   97,  108,   83,    0,   61,    0,   69,   78,   70,
        0,    0,   67,   75,   65,   76,   66,   77,    0,   56,
        1,    2,   68,   57,   53,    0,    0,   53,   53,    0,
       53,   52,   52,   52,   52,   74,   80,   82,   81,   73,
       50,    0,    0,   71,   50,   50,   50,   50,   50,   50,

       50,   50,   50,   50,   50,   50,   50,   10,   50,   50,
       50,   50,   50,   50,   19,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   72,   79,
       61,    0,    0,    0,    0,   54,    0,    0,   62,    0,
       56,    2,    0,   57,    0,   55,   53,   53,   53,   53,
        0,   51,   52,   52,   52,   52,   64,   63,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   17,   50,
       50,   50,   21,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,    0,

        0,    0,    0,    0,   56,    0,   57,   55,   53,    0,
        0,   51,    0,   51,   51,   52,   50,   50,   50,   50,
       50,   50,   50,    3,   42,   50,    5,    6,   50,   50,
       50,   50,   50,   13,   14,   50,   50,   18,   50,   50,
       22,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   36,   50,   50,    0,    0,    0,    0,
        0,    0,   51,   51,    0,   58,   51,   51,   50,   50,
       50,   50,   50,   50,   50,    4,   50,    7,   50,   50,
       50,   50,   16,   50,   50,    0,   50,   50,   50,   27,
       50,   50,   50,   50,   50,   50,   34,   50,   50,   38,

        0,   59,    0,   60,   58,   51,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   11,   15,   50,   20,
        0,    0,   50,   50,   26,   28,   29,   30,   31,   32,
       50,   50,   50,   59,   60,   50,   50,   41,   50,   50,
       50,   50,   50,   43,   50,    9,   50,    0,    0,   50,
       50,   33,   50,   50,   39,   40,   44,   50,   50,   50,
       49,    8,   50,    0,    0,   24,   25,   35,   37,   46,
       50,   50,   45,    0,   23,   50,   50,    0,   50,   50,
       12,   50,   50,   50,   48,   47,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   20,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   29,   29,   29,   30,   31,
       32,   33,   33,   33,   33,   34,   33,   35,   33,   36,
       33,   33,   37,   38,   39,   33,   33,   40,   33,   33,
       41,   42,   43,   44,   45,    1,   46,   47,   48,   49,

       50,   51,   52,   53,   54,   33,   55,   56,   57,   58,
       59,   60,   33,   61,   62,   63,   64,   65,   66,   67,
       68,   69,   70,   71,   72,   73,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[74] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    4,    1,
        1,    1,    1,    1,    1,    5,    1,    6,    6,    7,
        7,    1,    1,    1,    1,    1,    3,    7,    7,    7,
        7,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        1,    3,    1,    1,    8,    6,    6,    7,    7,    7,
        6,    8,    8,    8,    8,    8,    8,    9,    8,    8,
        9,    8,    9,    8,    9,    8,    9,    8,    8,    1,
        1,    1,    1
    } ;

static const flex_int16_t yy_base[398] =
    {   0,
        0,    0,  680,  681,   72,   75,  654,   74,  653,   73,
      635,  681,  681,  651,   69,  681,   70,   68,   80,  101,
      153,  681,  681,   66,  650,   74,  681,    0,   95,  681,
      681,  649,  101,  609,   47,   56,   53,   67,   51,  613,
       86,  612,  620,   95,  601,  136,  609,  614,  681,   88,
      681,  681,  124,  681,  105,  173,  134,  681,  681,  681,
      121,  148,  681,  681,  681,  681,  681,  681,  650,  200,
      681,    0,  681,  208,  114,  225,  178,  116,  126,  649,
      146,    0,  150,  130,  149,  639,  681,  681,  681,  638,
        0,  164,  620,  681,  148,  611,  601,  596,  605,  606,

      593,  596,  604,  591,  606,  165,  600,  586,  587,  584,
      584,  587,  584,  581,    0,  597,  169,  584,  200,  582,
      126,  187,  586,  579,  632,   70,  193,  583,  681,  681,
      263,  630,  234,  254,    0,  681,  252,    0,  681,  261,
      681,    0,  270,  681,  280,  285,   54,  681,  601,  578,
        0,  279,  214,  681,  599,  576,  681,  681,  577,  571,
      571,  567,  581,  565,  561,  565,  567,  576,  571,  559,
      559,  173,  572,  570,  566,  558,  564,  567,    0,  553,
      559,  556,    0,  557,  554,  544,  542,  544,  546,  553,
      539,  537,  537,  549,  539,  543,  547,  549,  538,  302,

      339,  268,  382,  304,  343,  310,  386,  681,  681,  164,
      232,  273,  333,  277,  270,  681,  541,  535,  541,  540,
      526,  538,  529,    0,    0,  531,    0,    0,  529,  521,
      529,  518,  525,    0,    0,  519,  516,    0,  524,  519,
      572,  513,  497,  494,  491,  502,  489,  493,  497,  485,
      482,  464,  467,    0,  455,  467,  251,    0,  275,    0,
      425,  434,  301,  681,  377,  438,  482,  458,  455,  458,
      450,  447,  455,  462,  459,    0,  456,    0,  447,  448,
      453,  443,    0,  442,  449,  293,  433,  439,  434,    0,
      442,  439,  440,  424,  433,  431,    0,  421,  424,    0,

      442,  446,  455,  464,  681,  681,  320,  423,  416,  404,
      403,  401,  403,  374,  375,  373,    0,    0,  389,    0,
      375,  368,  376,  377,    0,    0,    0,    0,    0,    0,
      372,  372,  365,  681,  681,  357,  367,    0,  368,  354,
      369,  364,  363,    0,  343,    0,  331,  320,  325,  321,
      317,    0,  329,  326,    0,    0,    0,  317,  327,  316,
        0,    0,  303,  309,  303,    0,    0,    0,    0,    0,
      288,  288,    0,  282,  681,  270,  266,  166,  158,  144,
      681,  101,   58,   20,    0,    0,  681,  520,  529,  533,
      540,  547,  556,  561,  563,  565,  567

    } ;

static const flex_int16_t yy_def[398] =
    {   0,
      387,    1,  387,  387,  387,  387,  387,  388,  387,  387,
      389,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  390,  390,  387,
      387,  387,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  387,  387,
      387,  387,  387,  387,  388,  387,  391,  387,  387,  387,
      389,  392,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  393,  387,  387,   20,  387,  387,  387,  387,  394,
      387,   21,  387,  387,  387,  387,  387,  387,  387,  387,
      390,  388,  389,  387,  390,  390,  390,  390,  390,  390,

      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  387,  387,
      387,  387,  387,  388,  395,  387,  389,  396,  387,  387,
      387,  393,  387,  387,  387,  387,  387,  387,  387,  387,
      397,  394,  387,  387,  387,  387,  387,  387,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  388,

      388,  389,  389,  387,  387,  387,  387,  387,  387,  397,
      397,  387,  387,  387,  387,  387,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  388,  201,  389,  203,
      387,  387,  387,  387,  387,  387,  387,  387,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  387,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,

      387,  387,  387,  387,  387,  387,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      387,  387,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  387,  387,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  387,  387,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  387,  387,  390,  390,  390,  390,  390,
      390,  390,  390,  387,  387,  390,  390,  387,  390,  390,
      387,  390,  390,  390,  390,  390,    0,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387

    } ;

static const flex_int16_t yy_nxt[755] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   22,   23,   24,   25,   26,   27,   28,   28,   28,
       28,   28,   28,   29,   28,   28,   28,   28,   29,   28,
       30,    4,   31,   32,   33,   34,   35,   36,   37,   38,
       39,   40,   28,   41,   28,   42,   28,   28,   28,   28,
       43,   44,   45,   46,   47,   48,   28,   28,   28,   49,
       50,   51,   52,   53,   53,   53,   53,   53,   53,   56,
       59,   64,  386,   69,   66,   70,   70,   70,   70,   86,
       87,   71,  148,   65,   67,   68,   72,   60,   89,   90,

       92,  104,  107,   93,   73,  102,  112,  103,  105,  113,
       56,  108,  129,  385,  106,   57,   74,  148,   75,   75,
       76,   76,  109,  195,  110,   53,   53,   53,   95,  136,
       77,  196,   96,  111,   78,   97,  115,   98,   99,   79,
       80,   92,  116,  117,   93,  100,   57,  120,  121,  147,
       77,  134,  134,  387,  148,  125,   81,  122,  130,  149,
      123,  384,   62,  155,   79,  137,  137,   80,   74,   56,
       82,   82,   82,   82,  131,  131,  131,  189,   92,  148,
      387,  150,   77,  153,  148,  156,   83,  154,  154,  383,
      145,   84,  145,  126,  190,  146,  146,  146,  146,  261,

      135,  147,   77,  159,  153,   57,  132,  382,   85,  148,
      160,  132,  154,  154,  138,  381,   84,   70,   70,   70,
       70,  171,  172,  261,  182,   70,   70,   70,   70,  140,
      141,  183,  191,  141,  230,  231,  133,  143,  144,   92,
       74,  144,   76,   76,   76,   76,  197,  192,  198,  140,
      141,  185,  154,  132,   77,  141,   56,  143,  144,   56,
      136,  186,  187,  144,  131,  131,  131,  262,   92,  202,
      202,  200,  200,  204,   77,  204,  136,  154,  205,  205,
      205,  205,  206,  136,  206,  259,  259,  207,  207,  207,
      207,  262,   57,   62,  211,   57,  132,  146,  146,  146,

      146,  132,  146,  146,  146,  146,  263,   56,  264,   62,
      267,  264,  212,  380,  213,  208,   62,  214,  208,  257,
      257,  205,  205,  205,  205,  263,  133,  207,  207,  207,
      207,  379,  268,  264,  215,  208,  264,  378,  213,  264,
      208,  321,  214,   57,   56,  265,  377,  265,  322,  376,
      266,  266,  266,  266,  375,  374,  258,  258,  258,  258,
      205,  205,  205,  205,  264,  336,  258,  258,  258,  258,
      373,  372,  371,  141,  370,  369,  141,  368,  337,  367,
       57,  366,  365,  364,  258,  258,  258,  258,  258,  258,
      136,  363,  362,  141,  266,  266,  266,  266,  141,  260,

      260,  260,  260,  207,  207,  207,  207,  361,  360,  260,
      260,  260,  260,  359,  358,  357,  144,  356,  355,  144,
      354,  353,  352,   62,  351,  350,  349,  260,  260,  260,
      260,  260,  260,  348,  347,  346,  144,  301,  345,  301,
      344,  144,  302,  302,  302,  302,  303,  343,  303,  342,
      341,  304,  304,  304,  304,  266,  266,  266,  266,  302,
      302,  302,  302,  302,  302,  302,  302,  340,  305,  339,
      338,  305,  304,  304,  304,  304,  334,  333,  332,  334,
      331,  304,  304,  304,  304,  330,  329,  328,  305,  327,
      326,  325,  324,  305,  335,  323,  334,  335,  320,  319,

      318,  334,  317,  316,  315,  314,  313,  312,  311,  310,
      309,  308,  307,  306,  335,  306,  300,  299,  298,  335,
       55,  297,   55,   55,   55,   55,   55,   55,   55,   61,
      296,   61,  295,   61,   61,   61,   61,   61,   91,   91,
       91,   91,   55,   55,  294,   55,  293,  292,   55,   61,
       61,  291,   61,  290,  289,   61,  142,  288,  142,  142,
      142,  142,  142,  142,  142,  152,  152,  152,  201,  201,
      203,  203,  210,  210,  287,  286,  285,  284,  283,  282,
      281,  280,  279,  278,  277,  276,  275,  274,  273,  272,
      271,  270,  269,  256,  255,  254,  253,  252,  251,  250,

      249,  248,  247,  246,  245,  244,  243,  242,  241,  240,
      239,  238,  237,  236,  235,  234,  233,  232,  229,  228,
      227,  226,  225,  224,  223,  222,  221,  220,  219,  218,
      217,  216,  216,  209,  209,   92,  199,   92,  194,  193,
      188,  184,  181,  180,  179,  178,  177,  176,  175,  174,
      173,  170,  169,  168,  167,  166,  165,  164,  163,  162,
      161,   62,  158,  157,  151,  139,  128,  127,  124,  119,
      118,  114,  101,   94,   88,   63,   62,   58,   54,  387,
        3,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,

      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387
    } ;

static const flex_int16_t yy_chk[755] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    5,    5,    5,    6,    6,    6,    8,
       10,   15,  384,   18,   17,   18,   18,   18,   18,   24,
       24,   19,  147,   15,   17,   17,   19,   10,   26,   26,

       29,   36,   37,   29,   19,   35,   39,   35,   36,   39,
       55,   37,   50,  383,   36,    8,   20,  147,   20,   20,
       20,   20,   38,  126,   38,   53,   53,   53,   33,   61,
       20,  126,   33,   38,   20,   33,   41,   33,   33,   20,
       20,   46,   41,   41,   46,   33,   55,   44,   44,   78,
       20,   57,   57,   75,   78,   46,   20,   44,   50,   79,
       44,  382,   61,   84,   20,   62,   62,   20,   21,   92,
       21,   21,   21,   21,   56,   56,   56,  121,   56,   78,
       75,   79,   21,   83,   81,   84,   21,   85,   83,  380,
       77,   21,   77,   46,  121,   77,   77,   77,   77,  210,

       57,   81,   21,   95,   85,   92,   56,  379,   21,   81,
       95,   56,   85,   83,   62,  378,   21,   70,   70,   70,
       70,  106,  106,  210,  117,   74,   74,   74,   74,   70,
       70,  117,  122,   70,  172,  172,   56,   74,   74,  133,
       76,   74,   76,   76,   76,   76,  127,  122,  127,   70,
       70,  119,  153,  133,   76,   70,  257,   74,   74,  134,
      137,  119,  119,   74,  131,  131,  131,  211,  131,  137,
      137,  134,  134,  140,   76,  140,  202,  153,  140,  140,
      140,  140,  143,  259,  143,  202,  202,  143,  143,  143,
      143,  211,  257,  137,  152,  134,  131,  145,  145,  145,

      145,  131,  146,  146,  146,  146,  212,  200,  215,  202,
      214,  212,  152,  377,  152,  146,  259,  152,  146,  200,
      200,  204,  204,  204,  204,  215,  131,  206,  206,  206,
      206,  376,  214,  215,  152,  146,  212,  374,  152,  263,
      146,  286,  152,  200,  201,  213,  372,  213,  286,  371,
      213,  213,  213,  213,  365,  364,  201,  201,  201,  201,
      205,  205,  205,  205,  263,  307,  201,  201,  201,  201,
      363,  360,  359,  205,  358,  354,  205,  353,  307,  351,
      201,  350,  349,  348,  201,  201,  201,  201,  201,  201,
      203,  347,  345,  205,  265,  265,  265,  265,  205,  203,

      203,  203,  203,  207,  207,  207,  207,  343,  342,  203,
      203,  203,  203,  341,  340,  339,  207,  337,  336,  207,
      333,  332,  331,  203,  324,  323,  322,  203,  203,  203,
      203,  203,  203,  321,  319,  316,  207,  261,  315,  261,
      314,  207,  261,  261,  261,  261,  262,  313,  262,  312,
      311,  262,  262,  262,  262,  266,  266,  266,  266,  301,
      301,  301,  301,  302,  302,  302,  302,  310,  266,  309,
      308,  266,  303,  303,  303,  303,  302,  299,  298,  302,
      296,  304,  304,  304,  304,  295,  294,  293,  266,  292,
      291,  289,  288,  266,  304,  287,  302,  304,  285,  284,

      282,  302,  281,  280,  279,  277,  275,  274,  273,  272,
      271,  270,  269,  268,  304,  267,  256,  255,  253,  304,
      388,  252,  388,  388,  388,  388,  388,  388,  388,  389,
      251,  389,  250,  389,  389,  389,  389,  389,  390,  390,
      390,  390,  391,  391,  249,  391,  248,  247,  391,  392,
      392,  246,  392,  245,  244,  392,  393,  243,  393,  393,
      393,  393,  393,  393,  393,  394,  394,  394,  395,  395,
      396,  396,  397,  397,  242,  241,  240,  239,  237,  236,
      233,  232,  231,  230,  229,  226,  223,  222,  221,  220,
      219,  218,  217,  199,  198,  197,  196,  195,  194,  193,

      192,  191,  190,  189,  188,  187,  186,  185,  184,  182,
      181,  180,  178,  177,  176,  175,  174,  173,  171,  170,
      169,  168,  167,  166,  165,  164,  163,  162,  161,  160,
      159,  156,  155,  150,  149,  132,  128,  125,  124,  123,
      120,  118,  116,  114,  113,  112,  111,  110,  109,  108,
      107,  105,  104,  103,  102,  101,  100,   99,   98,   97,
       96,   93,   90,   86,   80,   69,   48,   47,   45,   43,
       42,   40,   34,   32,   25,   14,   11,    9,    7,    3,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,

      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "cansi.l"
#line 25 "cansi.l"
#include <stdio.h>
#include <io.h>
#include <fcntl.h>
#include "wic.h"
#include "cansi.tab.h"

#define fileno _fileno
#define isatty _isatty

extern void yyerror(const char *);  /* prints grammar violation message */
static void comment(void);
static int check_type(void);
#line 763 "lex.yy.c"
#line 764 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

YYSTYPE * yyget_lval ( void );

void yyset_lval ( YYSTYPE * yylval_param  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param );

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param )
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
        YYSTYPE * yylval;
    
    yylval = yylval_param;

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 39 "cansi.l"

#line 993 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 388 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 681 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 40 "cansi.l"
{ comment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 41 "cansi.l"
{ /* consume //-comment */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 42 "cansi.l"
{ return(Y_AUTO); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 43 "cansi.l"
{ return(Y_BREAK); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 44 "cansi.l"
{ return(Y_CASE); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 45 "cansi.l"
{ return(Y_CHAR); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 46 "cansi.l"
{ return(Y_CONST); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 47 "cansi.l"
{ return(Y_CONTINUE); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 48 "cansi.l"
{ return(Y_DEFAULT); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 49 "cansi.l"
{ return(Y_DO); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 50 "cansi.l"
{ return(Y_DOUBLE); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 51 "cansi.l"
{ return(Y_LONG_DOUBLE); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 52 "cansi.l"
{ return(Y_ELSE); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 53 "cansi.l"
{ return(Y_ENUM); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 54 "cansi.l"
{ return(Y_EXTERN); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 55 "cansi.l"
{ return(Y_FLOAT); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 56 "cansi.l"
{ return(Y_FOR); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 57 "cansi.l"
{ return(Y_GOTO); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 58 "cansi.l"
{ return(Y_IF); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 59 "cansi.l"
{ return(Y_INLINE); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 60 "cansi.l"
{ return(Y_INT); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 61 "cansi.l"
{ return(Y_LONG); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 62 "cansi.l"
{ return(Y_LONG_LONG); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 63 "cansi.l"
{ return(Y_REGISTER); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 64 "cansi.l"
{ return(Y_RESTRICT); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 65 "cansi.l"
{ return(Y_RETURN); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 66 "cansi.l"
{ return(Y_SHORT); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 67 "cansi.l"
{ return(Y_SIGNED); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 68 "cansi.l"
{ return(Y_SIZEOF); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 69 "cansi.l"
{ return(Y_STATIC); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 70 "cansi.l"
{ return(Y_STRUCT); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 71 "cansi.l"
{ return(Y_SWITCH); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 72 "cansi.l"
{ return(Y_TYPEDEF); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 73 "cansi.l"
{ return(Y_UNION); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 74 "cansi.l"
{ return(Y_UNSIGNED); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 75 "cansi.l"
{ return(Y_VOID); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 76 "cansi.l"
{ return(Y_VOLATILE); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 77 "cansi.l"
{ return(Y_WHILE); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 78 "cansi.l"
{ return Y_ALIGNAS; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 79 "cansi.l"
{ return Y_ALIGNOF; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 80 "cansi.l"
{ return Y_ATOMIC; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 81 "cansi.l"
{ return Y_BOOL; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 82 "cansi.l"
{ return Y_COMPLEX; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 83 "cansi.l"
{ return Y_GENERIC; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 84 "cansi.l"
{ return Y_IMAGINARY; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 85 "cansi.l"
{ return Y_NORETURN; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 86 "cansi.l"
{ return Y_STATIC_ASSERT; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 87 "cansi.l"
{ return Y_THREAD_LOCAL; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 88 "cansi.l"
{ return Y_FUNC_NAME; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 89 "cansi.l"
{ yylval->string = _strdup(yytext); return IDENTIFIER; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 90 "cansi.l"
{ yylval->longlong = strtoull(yytext, 0, 10); return I_CONSTANT; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 91 "cansi.l"
{ yylval->longlong = strtoull(yytext, 0, 10); return I_CONSTANT; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 92 "cansi.l"
{ yylval->longlong = strtoull(yytext, 0, 10); return I_CONSTANT; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 93 "cansi.l"
{ yylval->longlong = strtoull(yytext, 0, 10); return I_CONSTANT; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 94 "cansi.l"
{ yylval->longdouble = strtold(yytext, NULL); return F_CONSTANT; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 95 "cansi.l"
{ yylval->longdouble = strtold(yytext, NULL); return F_CONSTANT; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 96 "cansi.l"
{ yylval->longdouble = strtold(yytext, NULL); return F_CONSTANT; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 97 "cansi.l"
{ yylval->longdouble = strtold(yytext, NULL); return F_CONSTANT; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 98 "cansi.l"
{ yylval->longdouble = strtold(yytext, NULL); return F_CONSTANT; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 99 "cansi.l"
{ yylval->longdouble = strtold(yytext, NULL); return F_CONSTANT; }
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 100 "cansi.l"
{ yylval->string = _strdup(yytext); return STRING_LITERAL; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 101 "cansi.l"
{ return Y_DOT_DOT_DOT; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 102 "cansi.l"
{ return Y_RSHIFT_EQUAL; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 103 "cansi.l"
{ return Y_LSHIFT_EQUAL; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 104 "cansi.l"
{ return Y_PLUS_EQUAL; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 105 "cansi.l"
{ return Y_MINUS_EQUAL; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 106 "cansi.l"
{ return Y_TIMES_EQUAL; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 107 "cansi.l"
{ return Y_DIVIDE_EQUAL; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 108 "cansi.l"
{ return Y_PERCENT_EQUAL; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 109 "cansi.l"
{ return Y_AND_EQUAL; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 110 "cansi.l"
{ return Y_XOR_EQUAL; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 111 "cansi.l"
{ return Y_OR_EQUAL; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 112 "cansi.l"
{ return Y_RSHIFT; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 113 "cansi.l"
{ return Y_LSHIFT; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 114 "cansi.l"
{ return Y_PLUS_PLUS; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 115 "cansi.l"
{ return Y_MINUS_MINUS; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 116 "cansi.l"
{ return Y_ARROW; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 117 "cansi.l"
{ return Y_AND_AND; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 118 "cansi.l"
{ return Y_OR_OR; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 119 "cansi.l"
{ return Y_LE; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 120 "cansi.l"
{ return Y_GE; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 121 "cansi.l"
{ return Y_EQ; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 122 "cansi.l"
{ return Y_NE; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 123 "cansi.l"
{ return Y_SEMICOLON; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 124 "cansi.l"
{ return  Y_LEFT_BRACE; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 125 "cansi.l"
{ return  Y_RIGHT_BRACE; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 126 "cansi.l"
{ return  Y_COMMA; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 127 "cansi.l"
{ return Y_COLON; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 128 "cansi.l"
{ return Y_EQUAL; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 129 "cansi.l"
{ return Y_LEFT_PAREN; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 130 "cansi.l"
{ return Y_RIGHT_PAREN; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 131 "cansi.l"
{ return Y_LEFT_BRACKET; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 132 "cansi.l"
{ return Y_RIGHT_BRACKET; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 133 "cansi.l"
{ return Y_DOT; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 134 "cansi.l"
{ return Y_AND; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 135 "cansi.l"
{ return Y_EXCLAMATION; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 136 "cansi.l"
{ return Y_TILDE; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 137 "cansi.l"
{ return Y_MINUS; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 138 "cansi.l"
{ return Y_PLUS; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 139 "cansi.l"
{ return Y_TIMES; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 140 "cansi.l"
{ return Y_DIVIDE; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 141 "cansi.l"
{ return Y_PERCENT; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 142 "cansi.l"
{ return Y_LT; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 143 "cansi.l"
{ return Y_GT; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 144 "cansi.l"
{ return Y_XOR; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 145 "cansi.l"
{ return Y_OR; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 146 "cansi.l"
{ return Y_QUESTION; }
	YY_BREAK
case 108:
/* rule 108 can match eol */
YY_RULE_SETUP
#line 148 "cansi.l"
{ /* whitespace separates tokens */ }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 149 "cansi.l"
{ /* discard bad characters */ }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 151 "cansi.l"
ECHO;
	YY_BREAK
#line 1602 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 388 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 388 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 387);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 151 "cansi.l"


int yywrap(void)        /* called at end of input */
{
    return 1;           /* terminate now */
}

static void comment(void)
{
    int c;

    while ((c = input()) != 0)
        if (c == '*')
        {
            while ((c = input()) == '*')
                ;

            if (c == '/')
                return;

            if (c == 0)
                break;
        }
    yyerror("unterminated comment");
}

static int check_type(void)
{
        return IDENTIFIER;
}

