#ifndef YYTOKENTYPE
#define T_INTEGER            0x03
#define T_SINGLECHAR         0x04
#define T_LONGINT            0x05
#define T_UNSINT             0x06
#define T_UNS_LONGINT        0x07
#define T_FLOATNUM           0x08
#define T_DOUBLENUM          0x09
#define T_ID                 0x0a
#define T_STRING             0x0b
#define T_LPAR               0x0c
#define T_RPAR               0x0d
#define T_LSQR               0x0e
#define T_RSQR               0x0f
#define T_DOT                0x10
#define T_ARROW              0x11
#define T_INCR               0x12
#define T_DECR               0x13
#define T_COMMA              0x14
#define T_AND                0x15
#define T_STAR               0x16
#define T_PLUS               0x17
#define T_MINUS              0x18
#define T_NOT                0x19
#define T_EXCLAIM            0x1a
#define T_SIZEOF             0x1b
#define T_DIV                0x1c
#define T_MOD                0x1d
#define T_LSHIFT             0x1e
#define T_RSHIFT             0x1f
#define T_LT                 0x20
#define T_LE                 0x21
#define T_GT                 0x22
#define T_GE                 0x23
#define T_EQ                 0x24
#define T_NE                 0x25
#define T_EXOR               0x26
#define T_OR                 0x27
#define T_LOGAND             0x28
#define T_LOGOR              0x29
#define T_QUEST              0x2a
#define T_COLON              0x2b
#define T_ASS                0x2c
#define T_STAR_ASS           0x2d
#define T_DIV_ASS            0x2e
#define T_MOD_ASS            0x2f
#define T_PLUS_ASS           0x30
#define T_MINUS_ASS          0x31
#define T_LSHIFT_ASS         0x32
#define T_RSHIFT_ASS         0x33
#define T_AND_ASS            0x34
#define T_EXOR_ASS           0x35
#define T_OR_ASS             0x36
#define T_SEMI               0x37
#define T_STATIC             0x38
#define T_EXTERN             0x39
#define T_TYPEDEF            0x3a
#define T_REGISTER           0x3b
#define T_AUTO               0x3c
#define T_CHAR               0x3d
#define T_SHORT              0x3e
#define T_INT                0x3f
#define T_LONG               0x40
#define T_UNSIGNED           0x41
#define T_SIGNED             0x42
#define T_FLOAT              0x43
#define T_DOUBLE             0x44
#define T_VOID               0x45
#define T_TYPE_ID            0x46
#define T_RBRACE             0x47
#define T_STRUCT             0x48
#define T_UNION              0x49
#define T_LBRACE             0x4a
#define T_ENUM               0x4b
#define T_CONST              0x4c
#define T_VOLATILE           0x4d
#define T_DOTDOT             0x4e
#define T_CASE               0x4f
#define T_DEFAULT            0x50
#define T_IF                 0x51
#define T_ELSE               0x52
#define T_SWITCH             0x53
#define T_WHILE              0x54
#define T_DO                 0x55
#define T_FOR                0x56
#define T_GOTO               0x57
#define T_CONTINUE           0x58
#define T_BREAK              0x59
#define T_RETURN             0x5a
typedef unsigned short yytokentype;
#define YYTOKENTYPE yytokentype
#endif
