/***************************************************************************
 * FILE: stdnoreturn.h (Macro to simulate the 'noreturn' specifier in C)
 *
 * =========================================================================
 *
 *                          Open Watcom Project
 *
 * Copyright (c) 2004-2025 The Open Watcom Contributors. All Rights Reserved.
 *
 *    This file is automatically generated. Do not edit directly.
 *
 * =========================================================================
 *
 * Description: This header is part of the C11 standard library. It
 *              provides a way for the programmer, at his/her option
 *              to introduce the specifier 'noreturn' into a C program.
 ***************************************************************************/

#ifndef _STDNORETURN_H_INCLUDED
#define _STDNORETURN_H_INCLUDED

#ifndef _ENABLE_AUTODEPEND
 #pragma read_only_file
#endif

#ifndef __cplusplus

#define noreturn _Noreturn

#endif

#endif
